pi_serial:
	gcc -o pi_serial pi_serial.c
	./pi_serial 1000000
pi_multi-thread:
	gcc -pthread -o pi_multi-thread pi_multi-thread.c
	./pi_multi-thread 1000000
clean:
	rm -f *.0 pi_multi-thread pi_serial	
